#:schema node_modules/wrangler/config-schema.json
name = "cf-rin-ai"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RIN_STATE"
id = "d4bea54d86e94d9ab69063eba1380dc3"

[ai]
binding = "AI"